spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DBgreenDine_Reservation?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081